name: Solar System Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: Welcome message
          run: echo "i am faslan"

        - name: List files
          run: ls

        - name: read file
          run: cat README.md
          
          
